// vuejs/src/main/webapp/app/entities/customer/customer-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="vuejsApp.customer.home.createOrEditLabel" v-text="$t('vuejsApp.customer.home.createOrEditLabel')">Create or edit a Customer</h2>
                <div>
                    <div class="form-group" v-if="customer.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="customer.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('vuejsApp.customer.firstName')" for="customer-firstName">First Name</label>
                        <input type="text" class="form-control" name="firstName" id="customer-firstName"
                            :class="{'valid': !$v.customer.firstName.$invalid, 'invalid': $v.customer.firstName.$invalid }" v-model="$v.customer.firstName.$model"  required/>
                        <div v-if="$v.customer.firstName.$anyDirty && $v.customer.firstName.$invalid">
                            <small class="form-text text-danger" v-if="!$v.customer.firstName.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('vuejsApp.customer.lastName')" for="customer-lastName">Last Name</label>
                        <input type="text" class="form-control" name="lastName" id="customer-lastName"
                            :class="{'valid': !$v.customer.lastName.$invalid, 'invalid': $v.customer.lastName.$invalid }" v-model="$v.customer.lastName.$model"  required/>
                        <div v-if="$v.customer.lastName.$anyDirty && $v.customer.lastName.$invalid">
                            <small class="form-text text-danger" v-if="!$v.customer.lastName.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('vuejsApp.customer.gender')" for="customer-gender">Gender</label>
                        <select class="form-control" name="gender" :class="{'valid': !$v.customer.gender.$invalid, 'invalid': $v.customer.gender.$invalid }" v-model="$v.customer.gender.$model" id="customer-gender"  required>
                            <option value="MALE" v-bind:label="$t('vuejsApp.Gender.MALE')">MALE</option>
                            <option value="FEMALE" v-bind:label="$t('vuejsApp.Gender.FEMALE')">FEMALE</option>
                            <option value="OTHER" v-bind:label="$t('vuejsApp.Gender.OTHER')">OTHER</option>
                        </select>
                        <div v-if="$v.customer.gender.$anyDirty && $v.customer.gender.$invalid">
                            <small class="form-text text-danger" v-if="!$v.customer.gender.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('vuejsApp.customer.email')" for="customer-email">Email</label>
                        <input type="text" class="form-control" name="email" id="customer-email"
                            :class="{'valid': !$v.customer.email.$invalid, 'invalid': $v.customer.email.$invalid }" v-model="$v.customer.email.$model"  required/>
                        <div v-if="$v.customer.email.$anyDirty && $v.customer.email.$invalid">
                            <small class="form-text text-danger" v-if="!$v.customer.email.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('vuejsApp.customer.phone')" for="customer-phone">Phone</label>
                        <input type="text" class="form-control" name="phone" id="customer-phone"
                            :class="{'valid': !$v.customer.phone.$invalid, 'invalid': $v.customer.phone.$invalid }" v-model="$v.customer.phone.$model"  required/>
                        <div v-if="$v.customer.phone.$anyDirty && $v.customer.phone.$invalid">
                            <small class="form-text text-danger" v-if="!$v.customer.phone.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('vuejsApp.customer.addressLine1')" for="customer-addressLine1">Address Line 1</label>
                        <input type="text" class="form-control" name="addressLine1" id="customer-addressLine1"
                            :class="{'valid': !$v.customer.addressLine1.$invalid, 'invalid': $v.customer.addressLine1.$invalid }" v-model="$v.customer.addressLine1.$model"  required/>
                        <div v-if="$v.customer.addressLine1.$anyDirty && $v.customer.addressLine1.$invalid">
                            <small class="form-text text-danger" v-if="!$v.customer.addressLine1.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('vuejsApp.customer.addressLine2')" for="customer-addressLine2">Address Line 2</label>
                        <input type="text" class="form-control" name="addressLine2" id="customer-addressLine2"
                            :class="{'valid': !$v.customer.addressLine2.$invalid, 'invalid': $v.customer.addressLine2.$invalid }" v-model="$v.customer.addressLine2.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('vuejsApp.customer.city')" for="customer-city">City</label>
                        <input type="text" class="form-control" name="city" id="customer-city"
                            :class="{'valid': !$v.customer.city.$invalid, 'invalid': $v.customer.city.$invalid }" v-model="$v.customer.city.$model"  required/>
                        <div v-if="$v.customer.city.$anyDirty && $v.customer.city.$invalid">
                            <small class="form-text text-danger" v-if="!$v.customer.city.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('vuejsApp.customer.country')" for="customer-country">Country</label>
                        <input type="text" class="form-control" name="country" id="customer-country"
                            :class="{'valid': !$v.customer.country.$invalid, 'invalid': $v.customer.country.$invalid }" v-model="$v.customer.country.$model"  required/>
                        <div v-if="$v.customer.country.$anyDirty && $v.customer.country.$invalid">
                            <small class="form-text text-danger" v-if="!$v.customer.country.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.customer.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./customer-update.component.ts">
</script>

// react/src/main/webapp/app/entities/customer/customer-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, reset } from './customer.reducer';
import { ICustomer } from 'app/shared/model/customer.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer, convertDateTimeToServer } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface ICustomerUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export interface ICustomerUpdateState {
  isNew: boolean;
}

export class CustomerUpdate extends React.Component<ICustomerUpdateProps, ICustomerUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentWillUpdate(nextProps, nextState) {
    if (nextProps.updateSuccess !== this.props.updateSuccess && nextProps.updateSuccess) {
      this.handleClose();
    }
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }
  }

  saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const { customerEntity } = this.props;
      const entity = {
        ...customerEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/customer');
  };

  render() {
    const { customerEntity, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="reactApp.customer.home.createOrEditLabel">
              <Translate contentKey="reactApp.customer.home.createOrEditLabel">Create or edit a Customer</Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : customerEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="customer-id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="customer-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="firstNameLabel" for="customer-firstName">
                    <Translate contentKey="reactApp.customer.firstName">First Name</Translate>
                  </Label>
                  <AvField
                    id="customer-firstName"
                    type="text"
                    name="firstName"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="lastNameLabel" for="customer-lastName">
                    <Translate contentKey="reactApp.customer.lastName">Last Name</Translate>
                  </Label>
                  <AvField
                    id="customer-lastName"
                    type="text"
                    name="lastName"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="genderLabel" for="customer-gender">
                    <Translate contentKey="reactApp.customer.gender">Gender</Translate>
                  </Label>
                  <AvInput
                    id="customer-gender"
                    type="select"
                    className="form-control"
                    name="gender"
                    value={(!isNew && customerEntity.gender) || 'MALE'}
                  >
                    <option value="MALE">{translate('reactApp.Gender.MALE')}</option>
                    <option value="FEMALE">{translate('reactApp.Gender.FEMALE')}</option>
                    <option value="OTHER">{translate('reactApp.Gender.OTHER')}</option>
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label id="emailLabel" for="customer-email">
                    <Translate contentKey="reactApp.customer.email">Email</Translate>
                  </Label>
                  <AvField
                    id="customer-email"
                    type="text"
                    name="email"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      pattern: {
                        value: '^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$',
                        errorMessage: translate('entity.validation.pattern', { pattern: '^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$' })
                      }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="phoneLabel" for="customer-phone">
                    <Translate contentKey="reactApp.customer.phone">Phone</Translate>
                  </Label>
                  <AvField
                    id="customer-phone"
                    type="text"
                    name="phone"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="addressLine1Label" for="customer-addressLine1">
                    <Translate contentKey="reactApp.customer.addressLine1">Address Line 1</Translate>
                  </Label>
                  <AvField
                    id="customer-addressLine1"
                    type="text"
                    name="addressLine1"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="addressLine2Label" for="customer-addressLine2">
                    <Translate contentKey="reactApp.customer.addressLine2">Address Line 2</Translate>
                  </Label>
                  <AvField id="customer-addressLine2" type="text" name="addressLine2" />
                </AvGroup>
                <AvGroup>
                  <Label id="cityLabel" for="customer-city">
                    <Translate contentKey="reactApp.customer.city">City</Translate>
                  </Label>
                  <AvField
                    id="customer-city"
                    type="text"
                    name="city"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="countryLabel" for="customer-country">
                    <Translate contentKey="reactApp.customer.country">Country</Translate>
                  </Label>
                  <AvField
                    id="customer-country"
                    type="text"
                    name="country"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/customer" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />
                  &nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />
                  &nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  customerEntity: storeState.customer.entity,
  loading: storeState.customer.loading,
  updating: storeState.customer.updating,
  updateSuccess: storeState.customer.updateSuccess
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CustomerUpdate);
