// vuejs/src/main/webapp/app/entities/customer/customer.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('vuejsApp.customer.home.title')" id="customer-heading">Customers</span>
            <router-link :to="{name: 'CustomerCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-customer">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('vuejsApp.customer.home.createLabel')">
                    Create new Customer
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && customers && customers.length === 0">
            <span v-text="$t('vuejsApp.customer.home.notFound')">No customers found</span>
        </div>
        <div class="table-responsive" v-if="customers && customers.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                    <th><span v-text="$t('vuejsApp.customer.firstName')">First Name</span></th>
                    <th><span v-text="$t('vuejsApp.customer.lastName')">Last Name</span></th>
                    <th><span v-text="$t('vuejsApp.customer.gender')">Gender</span></th>
                    <th><span v-text="$t('vuejsApp.customer.email')">Email</span></th>
                    <th><span v-text="$t('vuejsApp.customer.phone')">Phone</span></th>
                    <th><span v-text="$t('vuejsApp.customer.addressLine1')">Address Line 1</span></th>
                    <th><span v-text="$t('vuejsApp.customer.addressLine2')">Address Line 2</span></th>
                    <th><span v-text="$t('vuejsApp.customer.city')">City</span></th>
                    <th><span v-text="$t('vuejsApp.customer.country')">Country</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="customer in customers"
                    :key="customer.id">
                    <td>
                        <router-link :to="{name: 'CustomerView', params: {customerId: customer.id}}">{{customer.id}}</router-link>
                    </td>
                    <td>{{customer.firstName}}</td>
                    <td>{{customer.lastName}}</td>
                    <td v-text="$t('vuejsApp.Gender.' + customer.gender)">{{customer.gender}}</td>
                    <td>{{customer.email}}</td>
                    <td>{{customer.phone}}</td>
                    <td>{{customer.addressLine1}}</td>
                    <td>{{customer.addressLine2}}</td>
                    <td>{{customer.city}}</td>
                    <td>{{customer.country}}</td>
                    <td class="text-right">
                        <div class="btn-group flex-btn-group-container">
                            <router-link :to="{name: 'CustomerView', params: {customerId: customer.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'CustomerEdit', params: {customerId: customer.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(customer)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="vuejsApp.customer.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-customer-heading" v-bind:title="$t('vuejsApp.customer.delete.question')">Are you sure you want to delete this Customer?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-customer" v-text="$t('entity.action.delete')" v-on:click="removeCustomer()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./customer.component.ts">
</script>

// react/src/main/webapp/app/entities/customer/customer.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './customer.reducer';
import { ICustomer } from 'app/shared/model/customer.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ICustomerProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export class Customer extends React.Component<ICustomerProps> {
  componentDidMount() {
    this.props.getEntities();
  }

  render() {
    const { customerList, match } = this.props;
    return (
      <div>
        <h2 id="customer-heading">
          <Translate contentKey="reactApp.customer.home.title">Customers</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="reactApp.customer.home.createLabel">Create new Customer</Translate>
          </Link>
        </h2>
        <div className="table-responsive">
          {customerList && customerList.length > 0 ? (
            <Table responsive>
              <thead>
                <tr>
                  <th>
                    <Translate contentKey="global.field.id">ID</Translate>
                  </th>
                  <th>
                    <Translate contentKey="reactApp.customer.firstName">First Name</Translate>
                  </th>
                  <th>
                    <Translate contentKey="reactApp.customer.lastName">Last Name</Translate>
                  </th>
                  <th>
                    <Translate contentKey="reactApp.customer.gender">Gender</Translate>
                  </th>
                  <th>
                    <Translate contentKey="reactApp.customer.email">Email</Translate>
                  </th>
                  <th>
                    <Translate contentKey="reactApp.customer.phone">Phone</Translate>
                  </th>
                  <th>
                    <Translate contentKey="reactApp.customer.addressLine1">Address Line 1</Translate>
                  </th>
                  <th>
                    <Translate contentKey="reactApp.customer.addressLine2">Address Line 2</Translate>
                  </th>
                  <th>
                    <Translate contentKey="reactApp.customer.city">City</Translate>
                  </th>
                  <th>
                    <Translate contentKey="reactApp.customer.country">Country</Translate>
                  </th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {customerList.map((customer, i) => (
                  <tr key={`entity-${i}`}>
                    <td>
                      <Button tag={Link} to={`${match.url}/${customer.id}`} color="link" size="sm">
                        {customer.id}
                      </Button>
                    </td>
                    <td>{customer.firstName}</td>
                    <td>{customer.lastName}</td>
                    <td>
                      <Translate contentKey={`reactApp.Gender.${customer.gender}`} />
                    </td>
                    <td>{customer.email}</td>
                    <td>{customer.phone}</td>
                    <td>{customer.addressLine1}</td>
                    <td>{customer.addressLine2}</td>
                    <td>{customer.city}</td>
                    <td>{customer.country}</td>
                    <td className="text-right">
                      <div className="btn-group flex-btn-group-container">
                        <Button tag={Link} to={`${match.url}/${customer.id}`} color="info" size="sm">
                          <FontAwesomeIcon icon="eye" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.view">View</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${customer.id}/edit`} color="primary" size="sm">
                          <FontAwesomeIcon icon="pencil-alt" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.edit">Edit</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${customer.id}/delete`} color="danger" size="sm">
                          <FontAwesomeIcon icon="trash" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.delete">Delete</Translate>
                          </span>
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          ) : (
            <div className="alert alert-warning">
              <Translate contentKey="reactApp.customer.home.notFound">No Customers found</Translate>
            </div>
          )}
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ customer }: IRootState) => ({
  customerList: customer.entities
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Customer);
