// vuejs/src/main/webapp/app/entities/customer/customer.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('vuejsApp.customer.home.title')" id="customer-heading">Customers</span>
            <router-link :to="{name: 'CustomerCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-customer">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('vuejsApp.customer.home.createLabel')">
                    Create new Customer
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && customers && customers.length === 0">
            <span v-text="$t('vuejsApp.customer.home.notFound')">No customers found</span>
        </div>
        <div class="table-responsive" v-if="customers && customers.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                    <th><span v-text="$t('vuejsApp.customer.firstName')">First Name</span></th>
                    <th><span v-text="$t('vuejsApp.customer.lastName')">Last Name</span></th>
                    <th><span v-text="$t('vuejsApp.customer.gender')">Gender</span></th>
                    <th><span v-text="$t('vuejsApp.customer.email')">Email</span></th>
                    <th><span v-text="$t('vuejsApp.customer.phone')">Phone</span></th>
                    <th><span v-text="$t('vuejsApp.customer.addressLine1')">Address Line 1</span></th>
                    <th><span v-text="$t('vuejsApp.customer.addressLine2')">Address Line 2</span></th>
                    <th><span v-text="$t('vuejsApp.customer.city')">City</span></th>
                    <th><span v-text="$t('vuejsApp.customer.country')">Country</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="customer in customers"
                    :key="customer.id">
                    <td>
                        <router-link :to="{name: 'CustomerView', params: {customerId: customer.id}}">{{customer.id}}</router-link>
                    </td>
                    <td>{{customer.firstName}}</td>
                    <td>{{customer.lastName}}</td>
                    <td v-text="$t('vuejsApp.Gender.' + customer.gender)">{{customer.gender}}</td>
                    <td>{{customer.email}}</td>
                    <td>{{customer.phone}}</td>
                    <td>{{customer.addressLine1}}</td>
                    <td>{{customer.addressLine2}}</td>
                    <td>{{customer.city}}</td>
                    <td>{{customer.country}}</td>
                    <td class="text-right">
                        <div class="btn-group flex-btn-group-container">
                            <router-link :to="{name: 'CustomerView', params: {customerId: customer.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'CustomerEdit', params: {customerId: customer.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(customer)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="vuejsApp.customer.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-customer-heading" v-bind:title="$t('vuejsApp.customer.delete.question')">Are you sure you want to delete this Customer?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-customer" v-text="$t('entity.action.delete')" v-on:click="removeCustomer()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./customer.component.ts">
</script>

// angular/src/main/webapp/app/entities/customer/customer.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { ICustomer } from 'app/shared/model/customer.model';
import { AccountService } from 'app/core';
import { CustomerService } from './customer.service';

@Component({
  selector: 'jhi-customer',
  templateUrl: './customer.component.html'
})
export class CustomerComponent implements OnInit, OnDestroy {
  customers: ICustomer[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(
    protected customerService: CustomerService,
    protected jhiAlertService: JhiAlertService,
    protected eventManager: JhiEventManager,
    protected accountService: AccountService
  ) {}

  loadAll() {
    this.customerService
      .query()
      .pipe(
        filter((res: HttpResponse<ICustomer[]>) => res.ok),
        map((res: HttpResponse<ICustomer[]>) => res.body)
      )
      .subscribe(
        (res: ICustomer[]) => {
          this.customers = res;
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInCustomers();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: ICustomer) {
    return item.id;
  }

  registerChangeInCustomers() {
    this.eventSubscriber = this.eventManager.subscribe('customerListModification', response => this.loadAll());
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="angularApp.customer.home.title">Customers</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-customer" [routerLink]="['/customer/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="angularApp.customer.home.createLabel">
            Create new Customer
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="alert alert-warning" *ngIf="customers?.length === 0">
        <span jhiTranslate="angularApp.customer.home.notFound">No customers found</span>
    </div>
    <div class="table-responsive" *ngIf="customers?.length > 0">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="angularApp.customer.firstName">First Name</span></th>
            <th><span jhiTranslate="angularApp.customer.lastName">Last Name</span></th>
            <th><span jhiTranslate="angularApp.customer.gender">Gender</span></th>
            <th><span jhiTranslate="angularApp.customer.email">Email</span></th>
            <th><span jhiTranslate="angularApp.customer.phone">Phone</span></th>
            <th><span jhiTranslate="angularApp.customer.addressLine1">Address Line 1</span></th>
            <th><span jhiTranslate="angularApp.customer.addressLine2">Address Line 2</span></th>
            <th><span jhiTranslate="angularApp.customer.city">City</span></th>
            <th><span jhiTranslate="angularApp.customer.country">Country</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let customer of customers ;trackBy: trackId">
                <td><a [routerLink]="['/customer', customer.id, 'view' ]">{{customer.id}}</a></td>
                <td>{{customer.firstName}}</td>
                <td>{{customer.lastName}}</td>
                <td jhiTranslate="{{'angularApp.Gender.' + customer.gender}}">{{customer.gender}}</td>
                <td>{{customer.email}}</td>
                <td>{{customer.phone}}</td>
                <td>{{customer.addressLine1}}</td>
                <td>{{customer.addressLine2}}</td>
                <td>{{customer.city}}</td>
                <td>{{customer.country}}</td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/customer', customer.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/customer', customer.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', 'customer', { outlets: { popup: customer.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
