// vuejs/src/main/webapp/app/entities/customer/customer-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="vuejsApp.customer.home.createOrEditLabel" v-text="$t('vuejsApp.customer.home.createOrEditLabel')">Create or edit a Customer</h2>
                <div>
                    <div class="form-group" v-if="customer.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="customer.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('vuejsApp.customer.firstName')" for="customer-firstName">First Name</label>
                        <input type="text" class="form-control" name="firstName" id="customer-firstName"
                            :class="{'valid': !$v.customer.firstName.$invalid, 'invalid': $v.customer.firstName.$invalid }" v-model="$v.customer.firstName.$model"  required/>
                        <div v-if="$v.customer.firstName.$anyDirty && $v.customer.firstName.$invalid">
                            <small class="form-text text-danger" v-if="!$v.customer.firstName.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('vuejsApp.customer.lastName')" for="customer-lastName">Last Name</label>
                        <input type="text" class="form-control" name="lastName" id="customer-lastName"
                            :class="{'valid': !$v.customer.lastName.$invalid, 'invalid': $v.customer.lastName.$invalid }" v-model="$v.customer.lastName.$model"  required/>
                        <div v-if="$v.customer.lastName.$anyDirty && $v.customer.lastName.$invalid">
                            <small class="form-text text-danger" v-if="!$v.customer.lastName.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('vuejsApp.customer.gender')" for="customer-gender">Gender</label>
                        <select class="form-control" name="gender" :class="{'valid': !$v.customer.gender.$invalid, 'invalid': $v.customer.gender.$invalid }" v-model="$v.customer.gender.$model" id="customer-gender"  required>
                            <option value="MALE" v-bind:label="$t('vuejsApp.Gender.MALE')">MALE</option>
                            <option value="FEMALE" v-bind:label="$t('vuejsApp.Gender.FEMALE')">FEMALE</option>
                            <option value="OTHER" v-bind:label="$t('vuejsApp.Gender.OTHER')">OTHER</option>
                        </select>
                        <div v-if="$v.customer.gender.$anyDirty && $v.customer.gender.$invalid">
                            <small class="form-text text-danger" v-if="!$v.customer.gender.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('vuejsApp.customer.email')" for="customer-email">Email</label>
                        <input type="text" class="form-control" name="email" id="customer-email"
                            :class="{'valid': !$v.customer.email.$invalid, 'invalid': $v.customer.email.$invalid }" v-model="$v.customer.email.$model"  required/>
                        <div v-if="$v.customer.email.$anyDirty && $v.customer.email.$invalid">
                            <small class="form-text text-danger" v-if="!$v.customer.email.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('vuejsApp.customer.phone')" for="customer-phone">Phone</label>
                        <input type="text" class="form-control" name="phone" id="customer-phone"
                            :class="{'valid': !$v.customer.phone.$invalid, 'invalid': $v.customer.phone.$invalid }" v-model="$v.customer.phone.$model"  required/>
                        <div v-if="$v.customer.phone.$anyDirty && $v.customer.phone.$invalid">
                            <small class="form-text text-danger" v-if="!$v.customer.phone.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('vuejsApp.customer.addressLine1')" for="customer-addressLine1">Address Line 1</label>
                        <input type="text" class="form-control" name="addressLine1" id="customer-addressLine1"
                            :class="{'valid': !$v.customer.addressLine1.$invalid, 'invalid': $v.customer.addressLine1.$invalid }" v-model="$v.customer.addressLine1.$model"  required/>
                        <div v-if="$v.customer.addressLine1.$anyDirty && $v.customer.addressLine1.$invalid">
                            <small class="form-text text-danger" v-if="!$v.customer.addressLine1.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('vuejsApp.customer.addressLine2')" for="customer-addressLine2">Address Line 2</label>
                        <input type="text" class="form-control" name="addressLine2" id="customer-addressLine2"
                            :class="{'valid': !$v.customer.addressLine2.$invalid, 'invalid': $v.customer.addressLine2.$invalid }" v-model="$v.customer.addressLine2.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('vuejsApp.customer.city')" for="customer-city">City</label>
                        <input type="text" class="form-control" name="city" id="customer-city"
                            :class="{'valid': !$v.customer.city.$invalid, 'invalid': $v.customer.city.$invalid }" v-model="$v.customer.city.$model"  required/>
                        <div v-if="$v.customer.city.$anyDirty && $v.customer.city.$invalid">
                            <small class="form-text text-danger" v-if="!$v.customer.city.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('vuejsApp.customer.country')" for="customer-country">Country</label>
                        <input type="text" class="form-control" name="country" id="customer-country"
                            :class="{'valid': !$v.customer.country.$invalid, 'invalid': $v.customer.country.$invalid }" v-model="$v.customer.country.$model"  required/>
                        <div v-if="$v.customer.country.$anyDirty && $v.customer.country.$invalid">
                            <small class="form-text text-danger" v-if="!$v.customer.country.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.customer.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./customer-update.component.ts">
</script>

// angular/src/main/webapp/app/entities/customer/customer-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { ICustomer, Customer } from 'app/shared/model/customer.model';
import { CustomerService } from './customer.service';

@Component({
  selector: 'jhi-customer-update',
  templateUrl: './customer-update.component.html'
})
export class CustomerUpdateComponent implements OnInit {
  isSaving: boolean;

  editForm = this.fb.group({
    id: [],
    firstName: [null, [Validators.required]],
    lastName: [null, [Validators.required]],
    gender: [null, [Validators.required]],
    email: [null, [Validators.required, Validators.pattern('^[^@s]+@[^@s]+.[^@s]+$')]],
    phone: [null, [Validators.required]],
    addressLine1: [null, [Validators.required]],
    addressLine2: [],
    city: [null, [Validators.required]],
    country: [null, [Validators.required]]
  });

  constructor(protected customerService: CustomerService, protected activatedRoute: ActivatedRoute, private fb: FormBuilder) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ customer }) => {
      this.updateForm(customer);
    });
  }

  updateForm(customer: ICustomer) {
    this.editForm.patchValue({
      id: customer.id,
      firstName: customer.firstName,
      lastName: customer.lastName,
      gender: customer.gender,
      email: customer.email,
      phone: customer.phone,
      addressLine1: customer.addressLine1,
      addressLine2: customer.addressLine2,
      city: customer.city,
      country: customer.country
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const customer = this.createFromForm();
    if (customer.id !== undefined) {
      this.subscribeToSaveResponse(this.customerService.update(customer));
    } else {
      this.subscribeToSaveResponse(this.customerService.create(customer));
    }
  }

  private createFromForm(): ICustomer {
    return {
      ...new Customer(),
      id: this.editForm.get(['id']).value,
      firstName: this.editForm.get(['firstName']).value,
      lastName: this.editForm.get(['lastName']).value,
      gender: this.editForm.get(['gender']).value,
      email: this.editForm.get(['email']).value,
      phone: this.editForm.get(['phone']).value,
      addressLine1: this.editForm.get(['addressLine1']).value,
      addressLine2: this.editForm.get(['addressLine2']).value,
      city: this.editForm.get(['city']).value,
      country: this.editForm.get(['country']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ICustomer>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-customer-heading" jhiTranslate="angularApp.customer.home.createOrEditLabel">Create or edit a Customer</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="angularApp.customer.firstName" for="field_firstName">First Name</label>
                    <input type="text" class="form-control" name="firstName" id="field_firstName"
                           formControlName="firstName"/>
                    <div *ngIf="editForm.get('firstName').invalid && (editForm.get('firstName').dirty || editForm.get('firstName').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('firstName').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="angularApp.customer.lastName" for="field_lastName">Last Name</label>
                    <input type="text" class="form-control" name="lastName" id="field_lastName"
                           formControlName="lastName"/>
                    <div *ngIf="editForm.get('lastName').invalid && (editForm.get('lastName').dirty || editForm.get('lastName').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('lastName').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="angularApp.customer.gender" for="field_gender">Gender</label>
                    <select class="form-control" name="gender" formControlName="gender" id="field_gender">
                        <option value="MALE">{{'angularApp.Gender.MALE' | translate}}</option>
                        <option value="FEMALE">{{'angularApp.Gender.FEMALE' | translate}}</option>
                        <option value="OTHER">{{'angularApp.Gender.OTHER' | translate}}</option>
                    </select>
                    <div *ngIf="editForm.get('gender').invalid && (editForm.get('gender').dirty || editForm.get('gender').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('gender').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="angularApp.customer.email" for="field_email">Email</label>
                    <input type="text" class="form-control" name="email" id="field_email"
                           formControlName="email"/>
                    <div *ngIf="editForm.get('email').invalid && (editForm.get('email').dirty || editForm.get('email').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('email').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('email').errors.pattern" jhiTranslate="entity.validation.pattern" [translateValues]="{ pattern: 'Email' }">
                            This field should follow pattern for "Email".
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="angularApp.customer.phone" for="field_phone">Phone</label>
                    <input type="text" class="form-control" name="phone" id="field_phone"
                           formControlName="phone"/>
                    <div *ngIf="editForm.get('phone').invalid && (editForm.get('phone').dirty || editForm.get('phone').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('phone').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="angularApp.customer.addressLine1" for="field_addressLine1">Address Line 1</label>
                    <input type="text" class="form-control" name="addressLine1" id="field_addressLine1"
                           formControlName="addressLine1"/>
                    <div *ngIf="editForm.get('addressLine1').invalid && (editForm.get('addressLine1').dirty || editForm.get('addressLine1').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('addressLine1').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="angularApp.customer.addressLine2" for="field_addressLine2">Address Line 2</label>
                    <input type="text" class="form-control" name="addressLine2" id="field_addressLine2"
                           formControlName="addressLine2"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="angularApp.customer.city" for="field_city">City</label>
                    <input type="text" class="form-control" name="city" id="field_city"
                           formControlName="city"/>
                    <div *ngIf="editForm.get('city').invalid && (editForm.get('city').dirty || editForm.get('city').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('city').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="angularApp.customer.country" for="field_country">Country</label>
                    <input type="text" class="form-control" name="country" id="field_country"
                           formControlName="country"/>
                    <div *ngIf="editForm.get('country').invalid && (editForm.get('country').dirty || editForm.get('country').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('country').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
